---
title: "Blutzuckeranalyse"
author: "Tobias Anton"
date: "`r system(command = 'ddate', intern = T)`"
output: 
  html_document: 
    fig_width: 10
    highlight: tango
    theme: spacelab
---

```{r, message=F, warning=FALSE, include=FALSE}
source(paste0(Sys.getenv("PROJECT_HOME"), "./init.r"))
knitr::opts_chunk$set(echo = F, fig.path = "plots/", warning = F, message = F)
```

## Glancing at the data

### Average Glucose Level by Weekday

```{r tbl_BZ_by_day}
sugr %>% 
  group_by(Tag) %>% 
  summarize("avg. mg/dl" = round(mean(Messung, na.rm = T), 0),
            "SD mg/dl"   = round(sd(Messung, na.rm = T), 0)) %>% 
  knitr::kable()
```

Not sure if alarming health-wise, but from a data-wise viewpoint those SDs really are awful:

```{r plot_BZ_by_day}
sugr %>% 
  group_by(Tag) %>% 
  summarize("mean" = round(mean(Messung, na.rm = T), 0),
            "SD"   = round(sd(Messung, na.rm = T), 0)) %>% 
  ggplot(., aes(x = Tag, y = mean)) +
    geom_point(stat = "identity") +
    geom_errorbar(aes(ymin = mean - SD, ymax = mean + SD)) +
    labs(x = "", y = "Glucose level (mg/dl)") +
    theme_tufte()
```

Heatmapping Glucose-Levels by day & hour seems like a good idea:

```{r plot_heatmap_d_h}
ggplot(sugr, aes(x = Stunde, y = Tag, fill = Messung)) +
  geom_tile(color = "white", size = 0.1) +
  scale_fill_viridis(name = "Glucose Level (mg/dl)") +
  labs(x = NULL, y = NULL, title = "Glucose Levels per day and hour") +
  scale_x_continuous(breaks = 0:23) +
  coord_equal() + theme_tufte() +
  theme(legend.title    = element_text(size = 12),
        legend.text     = element_text(size = 10),
        legend.position = "bottom")
```